/*
 * Xiaoduo Chatbot open api
 *
 * xiaoduo chatbot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package xiaoduo
// MatchQuestionRsp struct for MatchQuestionRsp
type MatchQuestionRsp struct {
	// 响应码
	ErrorCode int32 `json:"error_code,omitempty"`
	Info string `json:"info,omitempty"`
	Data MatchQuestionRspAllOfData `json:"data,omitempty"`
}
