/*
 * Xiaoduo Chatbot open api
 *
 * xiaoduo chatbot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package xiaoduo
// MatchQuestionRspAllOfData struct for MatchQuestionRspAllOfData
type MatchQuestionRspAllOfData struct {
	MsgId string `json:"msg_id,omitempty"`
	UserId int64 `json:"user_id,omitempty"`
	Question string `json:"question,omitempty"`
	Answers []string `json:"answers,omitempty"`
	Options []string `json:"options,omitempty"`
	Recommend []string `json:"recommend,omitempty"`
	RelatedQuestions []string `json:"related_questions,omitempty"`
	HotQuestions []string `json:"hot_questions,omitempty"`
	Inspects []string `json:"inspects,omitempty"`
	State int32 `json:"state,omitempty"`
}
