/*
 * Xiaoduo Chatbot open api
 *
 * xiaoduo chatbot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package xiaoduo
// MatchQuestionRspAllOf struct for MatchQuestionRspAllOf
type MatchQuestionRspAllOf struct {
	Data MatchQuestionRspAllOfData `json:"data,omitempty"`
}
