/*
 * Xiaoduo Chatbot open api
 *
 * xiaoduo chatbot api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package xiaoduo
// Inspect struct for Inspect
type Inspect struct {
	Id string `json:"id,omitempty"`
	Question string `json:"question,omitempty"`
}
